### PR TITLE
Remove duplicate topic 1598

### LINKED ISSUE #1598: In location / topic profile, remove duplicate mention of topic
E.g. https://scholia.toolforge.org/organization/Q39988/topic/Q169917

currently looks like this: 
Screen Shot 2021-08-12 at 19 08 15

### PR DESCRIPTION
**Pull request by DanielFLopez**
fix #1598 

Screen Shot 2021-08-17 at 4 10 45 PM

### CODE REVIEW

**Comment by egonw** [comment]
@DanielFLopez, what is/was wrong with the patch https://github.com/WDscholia/scholia/commit/44fdd6979c022cbbee37923626f7002db49d331a ?

**Comment by DanielFLopez** [comment]
> @DanielFLopez, what is/was wrong with the patch [44fdd69](https://github.com/WDscholia/scholia/commit/44fdd6979c022cbbee37923626f7002db49d331a) ?

this code was duplicated, I think due to a merge so I have removed it.

Screen Shot 2021-08-23 at 2 19 00 PM

**Comment by carlinmack** [comment]
yep, it also appears at line 113 https://github.com/WDscholia/scholia/blob/4c1aa5db27a647091a520f86b3c10c05c9b14dfd/scholia/app/templates/base.html#L113

**Comment by carlinmack** [comment]
Can you check that it displays correctly with this PR for all aspect-subaspects?

- [ ] country - topic
- [ ] location - topic
- [ ] organization - topic

**Review by carlinmack — COMMENTED** [review]
Can you check that it displays correctly with this PR for all aspect-subaspects?

- [ ] country - topic
- [ ] location - topic
- [ ] organization - topic

**Comment by DanielFLopez** [comment]
I checked.
 
 * [x]  country - topic
 * [x]  location - topic
 * [x]  organization - topic

Screen Shot 2021-08-23 at 3 04 03 PM
Screen Shot 2021-08-23 at 3 02 41 PM
Screen Shot 2021-08-23 at 3 01 06 PM

**Review by carlinmack — APPROVED** [review]

**Review by egonw — APPROVED** [review]

**Comment by egonw** [comment]
@fnielsen, it's actually more than 5 lines, but the complexity is very simple: it was duplicated code.

**Pull request merged**
