### PR TITLE
Adding links to topics' items on their relative pages

### PR DESCRIPTION
**Pull request by Adafede**
Fixes # (issue number, if applicable) 
_Did not open an issue_

This PR adds Wikidata items of the topic illustrated.
There was no direct link to the item corresponding to the topic of the page which seemed suboptimal.
Plurals where also harmonized between pages.
No item was added for "use" as it looked fuzzy to me.
    
### Caveats

> Please list anything which has been left out of this PR or which should be considered before this PR is accepted
Check any of the following which apply:

* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  This change requires a documentation update
    * [ ]  I have made corresponding changes to the documentation
* [ ]  This change requires new dependencies (please list)

*If you make changes to the Python code*
  
* [ ]  My code passes the [tox](https://tox.readthedocs.io/en/latest/) check, I can receive warnings about tests, documentation or both

### Testing
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please also list any relevant details for your test configuration.

* Test A
* Test B

### Checklist
* [x] I have [commented](https://peps.python.org/pep-0008/#comments) my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [x] I have not used code from external sources without attribution
* [x] I have considered [accessibility](https://www.w3.org/standards/webdesign/accessibility) in my implementation 
* [x] There are no remaining debug statements (print, console.log, ...)

### CODE REVIEW

**Review by egonw — APPROVED** [review]

**Comment by Adafede** [comment]
@fnielsen Also rebased this one 😊

**Comment by fnielsen** [comment]
Your branch is confusingly called "master".

**Comment by fnielsen** [comment]
It is unclear to me what this is suppose to do. Does it relate to an issue?

For instance, on http://127.0.0.1:8100/ontology/ the link goes to http://127.0.0.1:8100/ontology/Q113145171 but there is not much there and the item is "type of chemical entity"

**Comment by fnielsen** [comment]
Do you want the links to go to https://scholia.toolforge.org/topic/Qxxx ?

**Comment by Adafede** [comment]
- Yes, sorry for the branch name, next ones will be more intuitive.
- I corrected the incorrect QID, sorry, was a missed copy/paste.
- I wanted to link each topic to its Wikidata item, but maybe it was indeed not the way to do?

**Comment by fnielsen** [comment]
I still do not understand this PR. For instance, http://127.0.0.1:8100/chemical-class/ has a link to http://127.0.0.1:8100/chemical-class/Q47154513. Would it not be more relevant to have it going to http://127.0.0.1:8100/topic/Q47154513. The former link show the class as an instance. 

For `git pull https://github.com/Adafede/scholia.git master`, I get "fatal: Not possible to fast-forward, aborting."

**Comment by Adafede** [comment]
@fnielsen Sorry, indeed it was absolutely not doing what I wanted. Should hopefully be clearer now

**Comment by fnielsen** [comment]
https://scholia.toolforge.org/chemical-class/

**Pull request merged**
