### PR TITLE
Add link to about 879

### LINKED ISSUE #879: Make About link visible from the menu bar directly
rather than through the dropdown. This will affect the "Help" and "FAQ" links as well, so let's consider them in context.

### PR DESCRIPTION
**Pull request by DanielFLopez**
fix #879 

add link visible to about and faq

Screen Shot 2021-09-03 at 4 35 21 PM

### CODE REVIEW

**Review by carlinmack — CHANGES_REQUESTED** [review]
Your PR fixes the issue, but creates another. Why do we now have a dropdown called Help with one item, Statistics?

**Comment by DanielFLopez** [comment]
> Your PR fixes the issue, but creates another. Why do we now have a dropdown called Help with one item, Statistics?

should I remove the help? and leave statistics?

**Review by carlinmack — APPROVED** [review]

**Review by Daniel-Mietchen — APPROVED** [review]
Looks good.

**Comment by fnielsen** [comment]
I have added a comment on the issue page https://github.com/WDscholia/scholia/issues/879#issuecomment-963289211 for why I do not see this is a good idea.

**Pull request closed without merging**
