### PR TITLE
Link for property 931

### LINKED ISSUE #520: Wrong link in column for property view
https://tools.wmflabs.org/scholia/P1249

### LINKED ISSUE #931: In property view, add link to Wikidata page
e.g. 
https://tools.wmflabs.org/scholia/P1249
should link to
https://www.wikidata.org/wiki/Property:P1249

### PR DESCRIPTION
**Pull request by DanielFLopez**
fix #931 

add a label name for property
add a link to Wikidata
add description

Screen Shot 2021-08-20 at 11 43 46 AM

> Also, are you fixing #520? you don't mention fixing the column links in the description of your PR

you are right, the one I have fixed is 931, because I'm not quite sure what to add in the column

### CODE REVIEW

**Comment by carlinmack** [comment]
1. add a label name for property
2. add a link to Wikidata
3. add description

1 and 2 are a duplicate of #1548. I think we should have "Property: " in the title to distinguish from the Q pages which could have the same title and be confusing for the user

**Comment by carlinmack** [comment]
Also, are you fixing #520? you don't mention fixing the links in the description of your PR

**Comment by DanielFLopez** [comment]
> Also, are you fixing #520? you don't mention fixing the column links in the description of your PR

you are right, the one I have fixed is 931, because I'm not quite sure what to add in the column

**Comment by carlinmack** [comment]
I'll add the description to my PR 👍

**Pull request closed without merging**
