### PR TITLE
create docker image and publish it

### PR DESCRIPTION
**Pull request by physikerwelt**
Fixes # (issue number, if applicable) 

    
### Caveats

> Please list anything which has been left out of this PR or which should be considered before this PR is accepted
Check any of the following which apply:

* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  This change requires a documentation update
    * [ ]  I have made corresponding changes to the documentation
* [ ]  This change requires new dependencies (please list)

*If you make changes to the Python code*
  
* [ ]  My code passes the [tox](https://tox.readthedocs.io/en/latest/) check, I can receive warnings about tests, documentation or both

### Testing
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please also list any relevant details for your test configuration.

* Test A
* Test B

### Checklist
* [ ] I have [commented](https://peps.python.org/pep-0008/#comments) my code, particularly in hard-to-understand areas
* [ ] My changes generate no new warnings
* [ ] I have not used code from external sources without attribution
* [ ] I have considered [accessibility](https://www.w3.org/standards/webdesign/accessibility) in my implementation 
* [ ] There are no remaining debug statements (print, console.log, ...)

### CODE REVIEW

**Comment by fnielsen** [comment]
I am struggling to understand this feature. For instance, 

"main" branch. Aren't our main branch called master at the moment. 

"schedule cron 30". Why should it run every 30 minute?

I am reading https://docs.github.com/en/enterprise-cloud@latest/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

**Comment by physikerwelt** [comment]
> I am struggling to understand this feature. For instance,
> 
> "main" branch. Aren't our main branch called master at the moment.

This was a typo. Fixed.

> 
> "schedule cron 30". Why should it run every 30 minute?

It runs once a day at 0:30 like crontab syntax. https://github.com/MaRDI4NFDI/scholia/pkgs/container/scholia/versions This is mainly to check for dependency regressions. Maybe you don't want that many images for scholias main repo.

> 
> I am reading https://docs.github.com/en/enterprise-cloud@latest/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

**Comment by WolfgangFahl** [comment]
IMHO it's much better to push docker images on release and properly use the releas tags. See e.g. the office mediawiki docker images at https://hub.docker.com/_/mediawiki

**Comment by WolfgangFahl** [comment]
also you might want to mark the images as "official" in comparsion to the other avaiable images by users see https://hub.docker.com/search?q=scholia

**Comment by physikerwelt** [comment]
> IMHO it's much better to push docker images on release and properly use the release tags. See e.g. the office mediawiki docker images at https://hub.docker.com/_/mediawiki

One can do that in addition. The native tag name 'nightly' should indicate that those packages are made for developers that want to test if their latest commits actually work;-)

**Comment by fnielsen** [comment]
Do we get a new persistent docker image each night the specified schedule or is it overwritten?

**Pull request merged**
