### PR TITLE
Update chemical.html

### PR DESCRIPTION
**Pull request by Adafede**
### Caveats

> None

### Testing

> None

### Checklist
* [ ] I have [commented](https://peps.python.org/pep-0008/#comments) my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [x] I have not used code from external sources without attribution
* [x] I have considered [accessibility](https://www.w3.org/standards/webdesign/accessibility) in my implementation 
* [x] There are no remaining debug statements (print, console.log, ...)

### CODE REVIEW

**Comment by Adafede** [comment]
Thank you, did not think about that.
Updated accordingly

**Comment by fnielsen** [comment]
I am wondering why this PR has no testing issues while, e.g., https://github.com/WDscholia/scholia/pull/2075 errs

**Comment by fnielsen** [comment]
The "All checks have passed" seems not to run Python tests. I have now run `tox` locally and find no errors for "Adafede-patch-3":
```
  flake8: commands succeeded
  pydocstyle: commands succeeded
  py37: commands succeeded
  py38: commands succeeded
  py39: commands succeeded
  congratulations :)
```
Yet https://github.com/WDscholia/scholia/pull/2080 which is based on the same master has errors in tox testing. I do not understand how this is possible.

**Comment by Adafede** [comment]
I was actually worried about my [branch](https://github.com/Adafede/scholia/runs/7741187731?check_suite_focus=true) because of the errors also but got it working here with the PR...

**Pull request merged**
