### PR TITLE
Add HTML Titles to all pages

### LINKED ISSUE #524: HTML titles for SEO
I just noticed that all pages in Scholia use the same HTML title. Adding meaningful HTML titles using the item label is a simple fix that's guaranteed to drive traffic and discoverability. 

You could format them in the following ways:

## Label only

 - Scholia: Denny Vrandečić
 - Scholia: Technical University of Denmark

## Label and QID

 - Scholia: Denny Vrandečić (Q18618629)
 - Scholia: Technical University of Denmark (Q1269766)

## Facet and label

 - Scholia: Author: Denny Vrandečić 
 - Scholia: Organization: Technical University of Denmark

I'd personally favor 1. Label only or 3. Facet and label. The QID doesn't add anything meaningful to the end user. Exposing the facet in the HTML title could be useful for items that can have multiple aspects.

If you end up implementing it, check how it affects traffic data.

### PR DESCRIPTION
**Pull request by carlinmack**
Close #524

### CODE REVIEW

**Comment by carlinmack** [comment]
PS it's not immediately obvious to me what the difference between "empty" and "index" pages are. I feel like they should both be called "index".

**Comment by curibe** [comment]
@carlinmack I think it is related to what Finn mentioned here: https://github.com/WDscholia/scholia/pull/1487#issuecomment-876777874

**Review by egonw — APPROVED** [review]
Looks good to me.

**Comment by egonw** [comment]
@carlinmack, can you rebase on master instead of merge?

**Pull request merged**
