### PR TITLE
Patch 7

### PR DESCRIPTION
**Pull request by larsgw**
### Description
  - adds "copy" button on reference export pages
  - adds a button-styled link titled "Cite" on work and software pages linking to the export page

### Caveats

> Please list anything which has been left out of this PR or which should be considered before this PR is accepted
Check any of the following which apply:

* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  This change requires a documentation update
    * [ ]  I have made corresponding changes to the documentation
* [ ]  This change requires new dependencies (please list)

> *If you make changes to the Python code*
  
* [ ]  My code passes the [tox](https://tox.readthedocs.io/en/latest/) check, I can receive warnings about tests, documentation or both

* Go to a work page and click the "Cite" button
* Click "Copy" and check that the output is copied to your clipboard
* Repeat for a software page

### Checklist
* [x] I have [commented](https://peps.python.org/pep-0008/#comments) my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [x] I have not used code from external sources without attribution
* [x] I have considered [accessibility](https://www.w3.org/standards/webdesign/accessibility) in my implementation 
* [x] There are no remaining debug statements (print, console.log, ...)

### CODE REVIEW

**Comment by larsgw** [comment]
I wasn't sure which one would be more visible (without being obtrusive of course).

**Comment by larsgw** [comment]
That's fair. I can move it to the top row of buttons, but that is part of the `base.html` template so I'll have to think a bit about the technical aspect.

**Comment by fnielsen** [comment]
"but that is part of the base.html" I see. I did not think of that.

**Comment by fnielsen** [comment]
It sounds fine!

**Pull request merged**
