### PR TITLE
Pr not warning 1529

### LINKED ISSUE #1442: GitHub action with tox test possibly not run
For this recent PR I do not see it report about the GitHub Action:

image

Neither see that it ran at https://github.com/fnielsen/scholia/actions/workflows/main.yml:

image

Finn, is my observation correct? Got a clue why it would not be running?

### LINKED ISSUE #1529: Why is the PR not warning about certain issues?
For instance, https://github.com/WDscholia/scholia/issues/1528 problem was not indicated

### PR DESCRIPTION
**Pull request by DanielFLopez**
fix #1529 
fix #1442 

I update the version of [setup-python](https://github.com/actions/setup-python) with v2

I also found that a test was failing and I fixed it but I must comment that I found a practice that should be improved, in the unit tests you should not make requests to services, within the Scholia code I found that a request is made to the query service of Wikidata but this is very heavy so it cannot be processed during the test, to avoid this problem create a mock-up of the request using [mock](https://pypi.org/project/mock/) library.

@egonw @fnielsen @carlinmack 

these are the actions of our fork
Screen Shot 2021-08-18 at 4 16 25 PM

### CODE REVIEW

**Comment by egonw** [comment]
Looks reasonable to me.

**Comment by fnielsen** [comment]
I am unsure whether tox is running ok with the current version of https://github.com/WDscholia/scholia/blob/master/.github/workflows/main.yml

At https://github.com/WDscholia/scholia/runs/6562398460?check_suite_focus=true is says only
```
py: commands succeeded
  congratulations :)
```
so I am not sure it has run.

**Comment by egonw** [comment]
I see this:

image

**Comment by fnielsen** [comment]
This has now been implemented with another PR:

https://github.com/WDscholia/scholia/pull/1987/commits/5a2d898257480a1fd9a618673814a0196bfc4bbf

Note the mock-up has not been implemented. It is not necessary!?

**Pull request closed without merging**
