### PR TITLE
Change empty by index and underscore by dash

### LINKED ISSUE #1332: Rename subaspects to dash from underscore
Instead of "organization_missing" name it "organization-missing".

### LINKED ISSUE #1339: curation pages should use dash instead of underscore

### LINKED ISSUE #1554: <aspect>_empty should be <aspect>-index
cito_empty should be cito-index

### PR DESCRIPTION
**Pull request by curibe**
fixed #1554 
fixed #1339 
fixed #1332 

## Rename and replace empty by index and underscore by dash

There are several files with the word _empty_ that must be replaced by word _index_. This PR do the following

### 1. Rename HTML files with the word _empty_

<details>
<summary>Click here to show files...</summary>

```
award_empty.html -> award_index.html
catalogue_empty.html -> catalogue_index.html
chemical_class_empty.html -> chemical_class_index.html
chemical_element_empty.html -> chemical_element_index.html
cito_empty.html -> cito_index.html
complex_empty.html -> complex_index.html
country_empty.html -> country_index.html
disease_empty.html -> disease_index.html
event_empty.html -> event_index.html
event_series_empty.html -> event_series_index.html
gene_empty.html -> gene_index.html
lexeme_empty.html -> lexeme_index.html
location_empty.html -> location_index.html
organization_empty.html -> organization_index.html
pathway_empty.html -> pathway_index.html
project_empty.html -> project_index.html
protein_empty.html -> protein_index.html
publisher_empty.html -> publisher_index.html
series_empty.html -> series_index.html
software_empty.html -> software_index.html
sponsor_empty.html -> sponsor_index.html
taxon_empty.html -> taxon_index.html
topic_empty.html -> topic_index.html
use_empty.html -> use_index.html
venue_empty.html -> venue_index.html
work_empty.html -> work_index.html
```
</details>

## 2. Change the name in view.py  where appears the files changed in 1 
Change in render_template and the function name. For example:
image

## 3. Rename html files with underscore with dash(hyphen)
 These files are:

<details>
<summary>Click to show files</summary>

```
404_chemical.html
404_doi.html
about_base.html
arxiv_to_quickstatements.html
author_base.html
author_curation.html
award_base.html
award_curation.html
award_index.html
catalogue_index.html
chemical_class.html
chemical_class_index.html
chemical_element.html
chemical_element_index.html
cito_base.html
cito_index.html
complex_index.html
country_index.html
country_topic.html
dataset_base.html
disease_base.html
disease_index.html
event_index.html
event_series.html
event_series_index.html
gene_base.html
gene_index.html
lexeme_index.html
location_index.html
location_topic.html
organization_base.html
organization_curation.html
organization_index.html
organization_topic.html
pathway_base.html
pathway_index.html
project_index.html
protein_base.html
protein_index.html
publisher_base.html
publisher_index.html
q_to_bibliography_templates.html
series_base.html
series_index.html
software_base.html
software_index.html
sponsor_index.html
taxon_base.html
taxon_index.html
text_to_topics.html
tools_base.html
topic_base.html
topic_curation.html
topic_index.html
use_index.html
venue_base.html
venue_cito.html
venue_curation.html
venue_index.html
work_base.html
work_cito.html
work_export.html
work_index.html
```
</details>

## 4. Change underscores by dash in HTML filenames inside view.py
For example:
image

## 5. Change the python function name invoked inside an HTML
For example:
image
 or have an aspect with the word _empty_:
```
scholia/app/templates/cito_index.html:{% set aspect = "cito_empty" %}
```

The files who must be changed here are:
<details>
<summary>Click here to show files...</summary>

- [x] cito_index.html
- [x] chemical-index-curation.html
- [x] organization.html
- [x] cito_base.html
- [x] base.html
- [x] chemical.html
- [x] chemical_element.html
- [x] complex_index.html
- [x] work_export.html
- [x] award.html
- [x] chemical_class.html
- [x] sponsor.html
- [x] venue.html
- [x] topic_curation.html
- [x] topic.html
- [x] venue_base.html
- [x] author_base.html
- [x] topic_base.html

</details>

## 6. Rename SPARQL files with the word empty
```
cito_empty_article-counts.sparql
cito_empty_articles-by-year.sparql
cito_empty_journal-counts.sparql
cito_empty_statistics.sparql
complex_empty_statistics.sparql
```

## 7. Change underscores by dash in aspect part  of SPARQL filename

Files that will be renamed:

<details> 
<summary> Click to show  files </summary>

```
chemical_class_class-hierarchy.sparql
chemical_class_identifiers.sparql
chemical_class_publications-per-year.sparql
chemical_class_recent-literature.sparql
chemical_class_related-chemicals.sparql
chemical_element_allotropes.sparql
chemical_element_isotopes.sparql
chemical_element_recent-literature.sparql
cito_index_article-counts.sparql
cito_index_articles-by-year.sparql
cito_index_journal-counts.sparql
cito_index_statistics.sparql
complex_index_statistics.sparql
country_topic_authors.sparql
country_topic_coauthors-graph.sparql
country_topic_cocitations-graph.sparql
event_series_events.sparql
event_series_list.sparql
event_series_map.sparql
event_series_people.sparql
event_series_proceedings-publications.sparql
event_series_recent-publications.sparql
event_series_timeline.sparql
event_series_topics.sparql
organization_missing_authors-no-initials.sparql
organization_missing_authors-with-initials.sparql
organization_missing_authors.sparql
organization_topic_recent-literature.sparql
pathway_optional_data_values.sparql
venue_cito_articles-by-intention.sparql
venue_cito_incoming-bubble.sparql
venue_cito_incoming.sparql
venue_cito_most-reused-articles.sparql
venue_cito_outgoing-bubble.sparql
venue_cito_outgoing.sparql
```
</details> 

**Note:** `organization-curation.html` is still using the missing word inside it and also all SPARQL files related to it

## 8. Change aspect in HTML files where SPARQL filename was changed in item 7

Files with underscore in `aspect`. For example:
image

These files are:

```
chemical-class.html
chemical-element.html
country-topic.html
event-series-index.html
event-series.html
organization-curation.html
organization-topic.html
venue-cito.html
``` 
One result:
image

### CODE REVIEW

**Comment by fnielsen** [comment]
It is actually "award-index" instead of "award_index"

**Comment by fnielsen** [comment]
The underscore for the Python function should be maintained as award_index.

**Comment by curibe** [comment]
@fnielsen do you want me to handle that in this PR too. I was thinking to resolve that in another PR and link this other issues:
#1339, #1332

**Comment by curibe** [comment]
Anyway, don't worry, I think it can handle here. I will link the other issues too

**Pull request merged**
