### PR TITLE
Add sponsors to event aspect

### PR DESCRIPTION
**Pull request by cthoyt**
### Description

This pull request lists sponsors on the event aspect using the following SPARQL:

```sparql
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT ?item ?itemLabel ?itemDescription
WHERE {
  target: wdt:P859 ?item .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```

This PR does not change any python nor javascript code. It adds a new `h2`-level header for sponsors under "people". The following example shows the sponsors for the 16th Annual International Biocuration Conference (https://www.wikidata.org/wiki/Q111430238):

Screenshot 2022-12-02 at 00 46 20

### Caveats

Not sure what other properties of a sponsor might be nice to include on this page.

Check any of the following which apply:

* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  This change requires a documentation update
    * [ ]  I have made corresponding changes to the documentation
* [ ]  This change requires new dependencies (please list)

*If you make changes to the Python code*
  
* [ ]  My code passes the [tox](https://tox.readthedocs.io/en/latest/) check, I can receive warnings about tests, documentation or both

### Testing
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please also list any relevant details for your test configuration.

* Test A
* Test B

### Checklist
* [x] I have [commented](https://peps.python.org/pep-0008/#comments) my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [x] I have not used code from external sources without attribution
* [x] I have considered [accessibility](https://www.w3.org/standards/webdesign/accessibility) in my implementation 
* [x] There are no remaining debug statements (print, console.log, ...)

### CODE REVIEW

**Comment by cthoyt** [comment]
cc @lubianat

**Comment by fnielsen** [comment]
I changed it a bit with https://github.com/WDscholia/scholia/pull/2192:
* Change column name
* Explicit URL to sponsor aspect
Hope that is ok.

**Comment by cthoyt** [comment]
Thanks @fnielsen ! Next time you can also just push directly to the original PR to avoid making duplicate branches and PRs

**Comment by fnielsen** [comment]
Thanks. My git capabilities are not that great :)

You change is running on toolforge now: https://scholia.toolforge.org/event/Q111430238#sponsors

**Pull request closed without merging**
