### PR TITLE
Fix wrong link country topic 1547

### LINKED ISSUE #1547: Wrong links in "Authors of the country" panel for country-topic aspect
Example: https://scholia.toolforge.org/country/Q33/topic/Q2539

Both author and example work is wrong

### PR DESCRIPTION
**Pull request by DanielFLopez**
fix #1547

### CODE REVIEW

**Review by Daniel-Mietchen — APPROVED** [review]
Looks good and works fine.

**Comment by fnielsen** [comment]
As far as I can see this add a "/" as the base of the directory. We previously had the root wmflabs.org/scholia/ which means that "/" was questionable. It is a question of whether this is a relic or we should maintain it. I think it should be possible to change "linkPrefixes" instead.

**Comment by egonw** [comment]
> As far as I can see this add a "/" as the base of the directory. We previously had the root wmflabs.org/scholia/ which means that "/" was questionable. It is a question of whether this is a relic or we should maintain it. I think it should be possible to change "linkPrefixes" instead.

@fnielsen, can you clarify what the next step is. Is this a question? Does it need a change in the code? Who is going to take the next step? Stating such explicitly will help keep momentum, because people have clear what is expected from them.

**Comment by fnielsen** [comment]
@egonw

> can you clarify what the next step is

I have now created an issue: https://github.com/WDscholia/scholia/issues/1700

**Comment by fnielsen** [comment]
This is superceded by https://github.com/WDscholia/scholia/pull/1702

**Pull request closed without merging**
