### PR TITLE
More functionality in the ontology aspect

### PR DESCRIPTION
**Pull request by egonw**
### Description
The ontology aspect did not provide a lot of information yet. I'm working with @andrawaag on making this aspect more useful. cc @jmillanacosta
    
### Caveats

* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  This change requires a documentation update
    * [ ]  I have made corresponding changes to the documentation
* [ ]  This change requires new dependencies (please list)

### Testing

* [ontology/Q55118285](https://scholia.toolforge.org/ontology/Q55118285)
* [ontology/Q1389366](https://scholia.toolforge.org/ontology/Q1389366)
* [ontology/Q116446479](https://scholia.toolforge.org/ontology/Q116446479)

### Checklist
* [x] I have [commented](https://peps.python.org/pep-0008/#comments) my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [x] I have not used code from external sources without attribution
* [ ] I have considered [accessibility](https://www.w3.org/standards/webdesign/accessibility) in my implementation 
* [x] There are no remaining debug statements (print, console.log, ...)

### CODE REVIEW

**Comment by egonw** [comment]
Screenshot of the initial, new data table:

image

**Comment by egonw** [comment]
Added a panel to list used ontologies:

image

**Comment by egonw** [comment]
@andrawaag, it would be nice if you can have a look. It does not implement all ideas from our meeting last Thursday yet, but I need a shape first now.

**Comment by egonw** [comment]
Entity Schema is here, but doesn't shed much light on what panel to add next: https://www.wikidata.org/wiki/EntitySchema:E368

**Comment by egonw** [comment]
Okay, making an exec call here. This PR is now feature complete. Other additions can be added later in other PRs.

**Comment by fnielsen** [comment]
Running: https://scholia.toolforge.org/ontology/

**Pull request merged**
